@startmindmap
* Разработка человеческого\nфактора
** Исследование факторов
*** Составили список факторов
*** Исследовали литературу
*** Исследование зависимости влияния факторов\nна определенные физические параметры
** Построение модели
*** Базовая модель
@endmindmap